name: todo_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.9.0
  flutter_local_notifications: ^19.5.0
  permission_handler: ^11.0.0
  workmanager: ^0.6.0
  intl: ^0.20.2
  pdf: ^3.11.1
  googleapis: ^11.3.0
  provider: ^6.1.1
  timezone: ^0.10.0
  device_info_plus: ^9.1.2
  share_plus: ^7.2.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png